spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_Management
    username: root
    password: 456741

  jpa:
    hibernate:
      ddl-auto: update

amazonProperties:
  accessKey:
  secretKey: